version: 0.2

phases:
  pre_build:
    commands:
      - IMAGE_NAME="${REPOSITORY_URI}:$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)"
      - echo $IMAGE_NAME
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - echo Build started on $(date)
      - DEFAULT=`pwd`
      - docker build --tag ${IMAGE_NAME} ./app/
      - docker push ${IMAGE_NAME}
      - cd ${DEFAULT}
  post_build:
    commands:
      - echo Build completed on $(date)
      - printf '{"Parameters":{"DockerImage":"%s"}}' ${IMAGE_NAME} > config.json

artifacts:
  files: config.json