AWSTemplateFormatVersion: '2010-09-09'
Description: RDS database

Resources:

  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: "books_api_development"
      Engine: MySQL
      MasterUsername: duc
      MasterUserPassword: password123
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '5'
      DBSecurityGroups:
        - !Ref DatabaseSG

  DatabaseSG:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Security Group for RDS public access
      DBSecurityGroupIngress:
        - CIDRIP: 0.0.0.0/0

Outputs:

  DatabaseInstanceAddess:
    Description: ECS Task Execution Role
    Value: !GetAtt 'DatabaseInstance.Endpoint.Address'
    Export:
      Name: 'DatabaseInstanceAddress'

  DatabaseInstancePort:
    Description: ECS Task Execution Role
    Value: !GetAtt 'DatabaseInstance.Endpoint.Port'
    Export:
      Name: 'DatabaseInstancePort'